=== opentestingapi/hugo/content/specification/OpenTestApiSchema_v0.1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "OpenTestApi Json Schema Version 0.1",
  "type": "object",
  "properties": {
    "testapi": {
      "type": "string",
      "description": "Specifies the TestAPI version."
    },
    "id": {
      "type": "string",
      "description": "Identifier of the test case."
    },
    "description": {
      "type": "string",
      "description": "The informal description of the test case."
    },
    "injections": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "injectid": {
            "type": "string"
          },
          "service": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "connectstring": {
                "type": "string"
              },
              "username": {
                "type": "string"
              },
              "password": {
                "type": "string"
              },
              "custom": {
                "type": "object",
                "properties": {
                  "topic": {
                    "type": "string"
                  },
                  "group": {
                    "type": "string"
                  },
                  "method": {
                    "type": "string"
                  }
                }
              }
            },
            "required": [
              "type",
              "connectstring"
            ]
          },
          "checks": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "cron": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "timetolive": {
            "type": "string"
          },
          "sourcefile": {
            "type": "string"
          },
          "replacements": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "string"
                },
                "value": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "order": {
                        "type": "integer",
                        "minimum": 0
                      },
                      "list": {
                        "type": "string"
                      },
                      "regex": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "order"
                    ]
                  }
                },
                "maxlength": {
                  "type": "integer",
                  "minimum": 0
                }
              }
            },
            "minItems": 1,
            "uniqueItems": true
          }
        },
        "required": [
          "injectid",
          "service",
          "checks",
          "sourcefile"
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "checks": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "checkid": {
            "type": "string"
          },
          "service": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "connectstring": {
                "type": "string"
              },
              "username": {
                "type": "string"
              },
              "password": {
                "type": "string"
              },
              "custom": {
                "type": "object",
                "properties": {
                  "topic": {
                    "type": "string"
                  },
                  "group": {
                    "type": "string"
                  },
                  "method": {
                    "type": "string"
                  }
                }
              }
            },
            "required": [
              "type",
              "connectstring"
            ]
          },
          "expectedfile": {
            "type": "string"
          },
          "checktype": {
            "enum": ["equals", "contains"]
          },
          "maxwaitime": {
            "type": "string"
          },
          "active": {
            "type": "string"
          }
        },
        "required": [
          "checkid",
          "service",
          "expectedfile",
          "checktype"
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": [
    "testapi",
    "id",
    "description"
  ]
}

=== opentestingapi/hugo/content/specification/OpenTestApi_v0.1.json
{
  "testapi": "0.1",
  "id": "myproject:myexampleapplication:E2E:test1",
  "description" : "a hello world test project",
  "injections" : [
    {
      "injectid" : "myinjectID",
      "service" : {
        "type": "kafka",
        "connectstring":"http://mykafkabroker.com",
        "username": "myusername",
        "password": "dW5zZWN1cmUgcGFzc3dvcmQ=",
        "custom": {
          "topic": "mytopic",
          "group": "mygroup",
          "method": "post"
        }
      },
      "checks" : [
        "mycheck1",
        "mycheck2"
      ],
      "cron": [
        "5 * * * * ?" ,
        "15 * * * * ?"
      ],
      "timetolive": "60s",
      "sourcefile" : "testcase1/mysourcefile.txt",
      "replacements" : [
        {
          "key" : "#key1#",
          "value": [{
            "order": 1,
            "list": "v1_0|v2_|v3_|v5_00"
          },{
            "order": 2,
            "regex": "^[0-9]{2}$"
          }],
          "maxlength":5
        }
      ]
    }
  ],
  "checks" : [
    {
      "checkid" : "mycheckid1",
      "service" : {
        "type": "kafka",
        "connectstring":"http://mykafkabroker.com",
        "username": "myusername",
        "password": "dW5zZWN1cmUgcGFzc3dvcmQ=",
        "custom": {
          "topic": "mytopic",
          "group": "mygroup",
          "method": "post"
        }
      },
      "expectedfile" : "testcase1/myresultfile.txt",
      "checktype" : "equals",
      "maxwaitime" : "60s",
      "active" : "true"
    }
  ]
}
